/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        primary: "#b0c6ff",
        "primary-container": "#0058cb",
        secondary: "#b3c5fd",
        "secondary-container": "#324575",
        tertiary: "#ffb59b",
        "tertiary-container": "#a93802",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "on-primary": "#002d6e",
        "on-secondary": "#1a2e5d",
        "on-tertiary": "#5c1a00",
        "on-error": "#690005",
        "on-primary-container": "#cbd8ff",
        "on-secondary-container": "#a1b4eb",
        "on-tertiary-container": "#ffcebd",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-bright": "#393939",
        "surface-dim": "#131313",
        "on-surface-variant": "#c3c6d6",
        outline: "#8d90a0",
        "outline-variant": "#424654",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#0058ca",
        "primary-fixed": "#d9e2ff",
        "primary-fixed-dim": "#b0c6ff",
        "on-primary-fixed": "#001945",
        "on-primary-fixed-variant": "#00429b",
        "secondary-fixed": "#dae2ff",
        "secondary-fixed-dim": "#b3c5fd",
        "on-secondary-fixed": "#001847",
        "on-secondary-fixed-variant": "#324575",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-fixed-dim": "#ffb59b",
        "on-tertiary-fixed": "#380d00",
        "on-tertiary-fixed-variant": "#812800",
      },
      fontFamily: {
        "dm-sans": ["var(--font-dm-sans)", "sans-serif"],
        "source-sans-3": ["var(--font-source-sans)", "sans-serif"],
        display: ["var(--font-dm-sans)", "sans-serif"],
        body: ["var(--font-source-sans)", "sans-serif"],
        headline: ["var(--font-dm-sans)", "sans-serif"],
        label: ["var(--font-source-sans)", "sans-serif"],
      },
      borderRadius: {
        'xl': '1.5rem',
      },
      boxShadow: {
        'editorial': '0px 24px 48px rgba(0, 0, 0, 0.4)',
        'glass': '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
      }
    },
  },
  plugins: [],
};
